apiVersion: v1
entries:
  datadog:
  - appVersion: 6.2.0
    created: 2019-02-08T10:35:30.449256146+01:00
    description: DataDog Agent
    digest: f8db03af55f01d8f6c386f84f8127c620f262f587deb013befece3a70fd72a77
    home: https://www.datadoghq.com
    icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
    keywords:
    - monitoring
    - alerting
    - metric
    - Operations
    maintainers:
    - email: haissam@datadoghq.com
      name: hkaj
    - email: ilan@datadoghq.com
      name: irabinovitch
    - email: xavier.vello@datadoghq.com
      name: xvello
    name: datadog
    sources:
    - https://app.datadoghq.com/account/settings#agent/kubernetes
    - https://github.com/DataDog/datadog-agent
    - https://github.com/DataDog/docker-dd-agent
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/datadog-3.1.0.tgz
    version: 3.1.0
  demoliberty:
  - created: 2019-02-08T10:35:30.45033512+01:00
    description: Simple Liberty Demo
    digest: 157aa7c7d45d2cfadb692e1836f9d60a2745460d21eeb5bd7e8bd1ddde3311a1
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/charts/blob/master/helm/charts/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.3.0.tgz
    version: 1.3.0
  - created: 2019-02-08T10:35:30.450092856+01:00
    description: Simple Liberty Demo
    digest: a0742ab206add9684a16be86564f6a32f551cd14a6141fc71c85fb59f8fa3cc3
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.2.0.tgz
    version: 1.2.0
  - created: 2019-02-08T10:35:30.449847932+01:00
    description: Simple Liberty Demo
    digest: b587bf9cec1e6fe79cecdcd532310386e3d704b0def5994aa5adfea539eb136e
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.1.0.tgz
    version: 1.1.0
  - created: 2019-02-08T10:35:30.449516938+01:00
    description: Simple Liberty Demo
    digest: 56d8ecc05c39bc2caa668240fb33a1f31a14f10e281c9af0b59a741117d39c22
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.0.0.tgz
    version: 1.0.0
  devops-gitlab:
  - apiVersion: v1
    appVersion: 9.3.8-ce.0
    created: 2019-02-08T10:35:30.45062703+01:00
    description: A Helm chart for a complete DevOps Pipeline - GitLab CE
    digest: 25f52d71be0540379638e6dd02a5aade656975086b4c079ade9b7916261570c3
    home: http://gitlab.com
    icon: https://docs.gitlab.com/assets/images/gitlab-logo.svg
    keywords:
    - DevOps
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: devops-gitlab
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/devops-gitlab-3.1.0.tgz
    version: 3.1.0
  devops-jenkins:
  - apiVersion: v1
    appVersion: "2.132"
    created: 2019-02-08T10:35:30.451232427+01:00
    description: A Helm chart for a complete DevOps Pipeline - Jenkins
    digest: 93cb8db8ac7cd9d5fa480cc4e31e38c394ac489f3c620ee83225fe8c9ed15a46
    home: https://jenkins.io/
    icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
    keywords:
    - DevOps
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: devops-jenkins
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/devops-jenkins-3.1.0.tgz
    version: 3.1.0
  devops-ucd-agent:
  - apiVersion: v1
    appVersion: 7.0.0
    created: 2019-02-08T10:35:30.451480515+01:00
    description: A Helm chart for a complete DevOps Pipeline - IBM UrbanCode Deploy
      Agent
    digest: f3ba5df46a478e74d1ac4d25e039a7d97c5e68ca034e540427cf832ae73dad1d
    icon: https://github.com/niklaushirt/charts/raw/master/helm/charts/icons/urbancodedeployicon.png
    keywords:
    - DevOps
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: devops-ucd-agent
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/devops-ucd-agent-3.1.0.tgz
    version: 3.1.0
  devops-ucd-server:
  - apiVersion: v1
    appVersion: 7.0.0
    created: 2019-02-08T10:35:30.451725449+01:00
    description: A Helm chart for a complete DevOps Pipeline - IBM UrbanCode Deploy
      Server
    digest: 1c23648026e000f18e52c743f5e8366c009732ef14dfae05e245bb7130426758
    icon: https://github.com/niklaushirt/charts/raw/master/helm/charts/icons/urbancodedeployicon.png
    keywords:
    - DevOps
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: devops-ucd-server
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/devops-ucd-server-3.1.0.tgz
    version: 3.1.0
  gbapp:
  - apiVersion: v1
    created: 2019-02-08T10:35:30.452010371+01:00
    description: A Helm chart for Kubernetes
    digest: f7d1c42dd1a33afb1ddbc6e6adefd02bdd3735c34356403f0652bf8421a68312
    name: gbapp
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/gbapp-0.1.0.tgz
    version: 0.1.0
  kubernetes-dashboard:
  - appVersion: 1.7.1
    created: 2019-02-08T10:35:30.452308944+01:00
    description: General-purpose web UI for Kubernetes clusters
    digest: fa82020305d26e5f4652f7947d891390b98abb962bfac2af3f45ed7370ddc539
    keywords:
    - kubernetes
    - dashboard
    maintainers:
    - email: Kevin.Fox@pnnl.gov
      name: kfox1111
    name: kubernetes-dashboard
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/kubernetes-dashboard-3.1.0.tgz
    version: 3.1.0
  manageiq:
  - created: 2019-02-08T10:35:30.452533761+01:00
    description: ManageIQ Cloud Management Platform http://manageiq.org - default
      username/password is admin/smartvm
    digest: f5c7d0874e6b141652038521db71739ea6ea7d4012681d8deda67d85ba0eaa39
    home: http://fabric8.io/manageiq/
    icon: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
    maintainers:
    - email: fabric8@googlegroups.com
      name: Fabric8 Development Team
    name: manageiq
    sources:
    - http://github.com/fabric8io/fabric8-devops/manageiq
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/manageiq-2.2.327.tgz
    version: 2.2.327
  mariadb:
  - appVersion: 1.1.2
    created: 2019-02-08T10:35:30.458552167+01:00
    description: MariaDB is developed as open source software and as a relational
      database it provides an SQL interface for accessing data.
    digest: 14dc2de3407b6daa247a26ac38abc636d97a17f99423b528ed4b52a368c33d05
    engine: gotpl
    home: https://www.mariadb.org/
    keywords:
    - mariadb
    - mysql
    - database
    maintainers:
    - name: IBM Analytics
    name: mariadb
    sources:
    - https://github.com/IBM/charts/tree/master/stable
    tillerVersion: '>=2.4.0'
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/mariadb-3.1.0.tgz
    version: 3.1.0
  mongodb:
  - appVersion: 3.4.10
    created: 2019-02-08T10:35:30.458910846+01:00
    description: NoSQL document-oriented database that stores JSON-like documents
      with dynamic schemas, simplifying the integration of data in content-driven
      applications.
    digest: 088b2f0b5b081fafe0e9722252e6b803b113abae5478768f455418c32077d8e9
    engine: gotpl
    home: https://mongodb.org
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    keywords:
    - mongodb
    - database
    - nosql
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: mongodb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/mongodb-3.1.0.tgz
    version: 3.1.0
  nginx:
  - appVersion: 1.8.1
    created: 2019-02-08T10:35:30.459131318+01:00
    description: Nginx for Linux
    digest: e5d3fb32b2be50d873ada9b2e328419e189d215d5296714e8a86d5024ed3aa61
    home: https://github.com/kubernetes/helm
    icon: https://pbs.twimg.com/profile_images/567774844322713600/tYoVju31.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: guo@ca.ibm.com
      name: guo
    name: nginx
    sources:
    - https://hub.docker.com/_/nginx/
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/nginx-3.1.0.tgz
    version: 3.1.0
  nodered:
  - apiVersion: v1
    appVersion: 0.17.5
    created: 2019-02-08T10:35:30.459435606+01:00
    description: A Helm chart for NodeRed
    digest: 3b75b7ddec95bedab9fc69b6d8ce65ed67a0dac6d94c090b3a9e5da633794a07
    icon: https://github.com/niklaushirt/chartslocal/raw/master/icons/noderedicon.png
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: nodered
    sources:
    - https://github.com/niklaushirt/chartslocal
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/nodered-3.1.0.tgz
    version: 3.1.0
  openwhisk:
  - apiVersion: v1
    created: 2019-02-08T10:35:30.460133466+01:00
    description: A Helm chart to deploy Apache OpenWhisk for Kubernetes
    digest: 860329a1c3eb2a59d8246e8b545b6c97056b93a9e5dda8cf06e36adea76ccef1
    keywords:
    - Apache OpenWhisk
    maintainers:
    - email: dev@openwhisk.apache.org
      name: Apache OpenWhisk committers
    name: openwhisk
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/openwhisk-0.1.1.tgz
    version: 0.1.1
  sonarqube:
  - appVersion: "6.5"
    created: 2019-02-08T10:35:30.460709727+01:00
    description: Sonarqube is an open sourced code quality scanning tool
    digest: 20ac91ea732e2583fb8b73b83b4ea18b54f871b29ba9b6071d561f2ec8f75c5b
    home: https://www.sonarqube.org/
    icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
    keywords:
    - coverage
    - security
    - code
    - quality
    - DevOps
    maintainers:
    - email: rjkernick@gmail.com
      name: rjkernick
    name: sonarqube
    sources:
    - https://github.com/SonarSource/docker-sonarqube
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/sonarqube-3.1.0.tgz
    version: 3.1.0
  tomcat:
  - apiVersion: v1
    appVersion: "9"
    created: 2019-02-08T10:35:30.46093071+01:00
    description: Tomcat for Linux
    digest: 7c0c0714b4ac9a04bc257e89e74fc0cf72d931f11a412c216748ae50a0b3f66a
    home: https://hub.docker.com/_/tomcat/
    icon: http://tomcat.apache.org/images/tomcat.png
    keywords:
    - runtime
    name: tomcat
    sources:
    - https://github.com/docker-library/tomcat
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/tomcat-3.1.0.tgz
    version: 3.1.0
  velocity:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2019-02-08T10:35:30.461221837+01:00
    description: Deploys UrbanCode Velocity
    digest: ff7c0b9dd4f28af1202c0f46dc7fbdebf2f888c7038f0accf6e1c9ace727d76d
    keywords:
    - DevOps
    name: velocity
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/velocity-3.1.0.tgz
    version: 3.1.0
generated: 2019-02-08T10:35:30.448107872+01:00
