---
name: "manageiq"
home: "http://fabric8.io/manageiq/"
sources:
- "http://github.com/fabric8io/fabric8-devops/manageiq"
version: "2.2.327"
description: "ManageIQ Cloud Management Platform http://manageiq.org - default username/password\
  \ is admin/smartvm"
maintainers:
- name: "Fabric8 Development Team"
  email: "fabric8@googlegroups.com"
icon: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png"
