apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ucd-relay
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: "{{ .Release.Service }}"
  name: ucd-relay
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ucd-relay
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - image: ibmcom/ucdr:{{ .Values.tag }}
        name: ucd-relay
        ports:
        - containerPort: 7916
        - containerPort: 20080
        - containerPort: 20081
        resources: {}
      restartPolicy: Always
status: {}
