apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: kube-ops-view
    version: v0.8.1
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      application: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        application: {{ template "fullname" . }}
        version: v0.8.1
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
      - name: service
        # see https://github.com/hjacobs/kube-ops-view/releases
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        # remove this option to use built-in memory store
        - --redis-url=redis://kube-ops-view-redis:6379
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
