apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  selector:
    application: {{ template "fullname" . }}
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    NodePort: 32299
