apiVersion: v1
entries:
  datadog:
  - appVersion: 6.2.0
    created: 2018-07-17T09:41:33.942432+02:00
    description: DataDog Agent
    digest: 182077eb6932a44c0aea9df97564e887cf6261c0353c906079e61007954073fc
    home: https://www.datadoghq.com
    icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
    keywords:
    - monitoring
    - alerting
    - metric
    maintainers:
    - email: haissam@datadoghq.com
      name: hkaj
    - email: ilan@datadoghq.com
      name: irabinovitch
    - email: xavier.vello@datadoghq.com
      name: xvello
    name: datadog
    sources:
    - https://app.datadoghq.com/account/settings#agent/kubernetes
    - https://github.com/DataDog/datadog-agent
    - https://github.com/DataDog/docker-dd-agent
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/datadog-0.11.3.tgz
    version: 0.11.3
  demoliberty:
  - created: 2018-07-17T09:41:33.943648+02:00
    description: Simple Liberty Demo
    digest: ca7c4361f268e69df1dbc4facf73db543d1b483c889b739539090769834c9cc4
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/charts/blob/master/helm/charts/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.3.0.tgz
    version: 1.3.0
  - created: 2018-07-17T09:41:33.943341+02:00
    description: Simple Liberty Demo
    digest: ea9b55d3a9d57eadc9637ea0013282ad1420649e60bd68e4856eadc8e74c7550
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.2.0.tgz
    version: 1.2.0
  - created: 2018-07-17T09:41:33.943048+02:00
    description: Simple Liberty Demo
    digest: a744b4074d4fa608573a6887b84f34dcdc85323c39854811f1e54647f7fb379f
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.1.0.tgz
    version: 1.1.0
  - created: 2018-07-17T09:41:33.942723+02:00
    description: Simple Liberty Demo
    digest: 4f1710d98c86ae68c08cce4f9afe01442b94f1f89981c64d45fb5e924dacd2d9
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/demoliberty/raw/master/charts/stable/icons/icp.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: demoliberty
    sources:
    - https://github.com/niklaushirt/demoliberty
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/demoliberty-1.0.0.tgz
    version: 1.0.0
  gitlab-ce:
  - created: 2018-07-17T09:41:33.943926+02:00
    description: GitLab CE release
    digest: 1e023b20e615b8fd937f5ef58a0765e64f418852a13c30393ef0e050ccaa85ee
    home: http://gitlab.com
    icon: https://docs.gitlab.com/assets/images/gitlab-logo.svg
    keywords:
    - git
    - gitlab
    maintainers:
    - email: zhiweik@gmail.com
      name: Zhiwei
    name: gitlab-ce
    sources:
    - https://hub.docker.com/r/gitlab/gitlab-ce
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/gitlab-ce-9.3.8-ce.0.tgz
    version: 9.3.8-ce.0
  jenkins:
  - appVersion: "2.73"
    created: 2018-07-17T09:41:33.94479+02:00
    description: Open source continuous integration server. It supports multiple SCM
      tools including CVS, Subversion and Git. It can execute Apache Ant and Apache
      Maven-based projects as well as arbitrary scripts.
    digest: 730a5f3bfc1fd212c63338568016f00b82a19d2c4a5d62f8401191ea8d58103c
    home: https://jenkins.io/
    icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
    maintainers:
    - email: lachlan.evenson@microsoft.com
      name: lachie83
    - email: viglesias@google.com
      name: viglesiasce
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-jnlp-slave
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/jenkins-0.14.2.tgz
    version: 0.14.2
  kubernetes-dashboard:
  - appVersion: 1.7.1
    created: 2018-07-17T09:41:33.945199+02:00
    description: General-purpose web UI for Kubernetes clusters
    digest: bf5b44c94dc53acd00a52d694da6b18f5ddc6e4d69a7fccdc11ddbaf45fc429b
    keywords:
    - kubernetes
    - dashboard
    maintainers:
    - email: Kevin.Fox@pnnl.gov
      name: kfox1111
    name: kubernetes-dashboard
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/kubernetes-dashboard-0.4.2.tgz
    version: 0.4.2
  mariadb:
  - created: 2018-07-17T09:41:33.952208+02:00
    description: MariaDB is developed as open source software and as a relational
      database it provides an SQL interface for accessing data.
    digest: 81a4c1a6a17b16192b91baf167376114478f4a7a56ca6ad5a641f05fb913deb7
    engine: gotpl
    home: https://www.mariadb.org/
    keywords:
    - mariadb
    - mysql
    - database
    maintainers:
    - name: IBM Analytics
    name: mariadb
    sources:
    - https://github.com/IBM/charts/tree/master/stable
    tillerVersion: '>=2.4.0'
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/mariadb-1.1.2.tgz
    version: 1.1.2
  mongodb:
  - appVersion: 3.4.10
    created: 2018-07-17T09:41:33.95256+02:00
    description: NoSQL document-oriented database that stores JSON-like documents
      with dynamic schemas, simplifying the integration of data in content-driven
      applications.
    digest: 80be6e504a166646b56c1daa5f5135f4d58055c528d40f66faf08da1f464bd5d
    engine: gotpl
    home: https://mongodb.org
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    keywords:
    - mongodb
    - database
    - nosql
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: mongodb
    sources:
    - https://github.com/bitnami/bitnami-docker-mongodb
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/mongodb-0.4.18.tgz
    version: 0.4.18
  nginx:
  - created: 2018-07-17T09:41:33.952815+02:00
    description: Nginx for Linux
    digest: 0d1c565930c844dcc1c6fbfaa4abbfe175964134969e40985e16c88306757d97
    home: https://github.com/kubernetes/helm
    icon: https://pbs.twimg.com/profile_images/567774844322713600/tYoVju31.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: guo@ca.ibm.com
      name: guo
    name: nginx
    sources:
    - https://hub.docker.com/_/nginx/
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/nginx-1.8.1.tgz
    version: 1.8.1
  nodered:
  - apiVersion: v1
    created: 2018-07-17T09:41:33.953111+02:00
    description: A Helm chart for NodeRed
    digest: f577a43b2c030563835ab5d42c1e44af1a7dd36c0b6b2e60ed772f066b6ee180
    icon: https://github.com/niklaushirt/chartslocal/raw/master/icons/noderedicon.png
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: nodered
    sources:
    - https://github.com/niklaushirt/chartslocal
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/nodered-0.17.5.tgz
    version: 0.17.5
  openwhisk:
  - apiVersion: v1
    created: 2018-07-17T09:41:33.953872+02:00
    description: A Helm chart to deploy Apache OpenWhisk for Kubernetes
    digest: 860329a1c3eb2a59d8246e8b545b6c97056b93a9e5dda8cf06e36adea76ccef1
    keywords:
    - Apache OpenWhisk
    maintainers:
    - email: dev@openwhisk.apache.org
      name: Apache OpenWhisk committers
    name: openwhisk
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/openwhisk-0.1.1.tgz
    version: 0.1.1
  sonarqube:
  - appVersion: "6.5"
    created: 2018-07-17T09:41:33.954649+02:00
    description: Sonarqube is an open sourced code quality scanning tool
    digest: 7f566d1492d130b31652d0c6e4b3541892bdc30ea50ae4694ccf5a96cacc2db0
    home: https://www.sonarqube.org/
    icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
    keywords:
    - coverage
    - security
    - code
    - quality
    maintainers:
    - email: rjkernick@gmail.com
      name: rjkernick
    name: sonarqube
    sources:
    - https://github.com/SonarSource/docker-sonarqube
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/sonarqube-0.2.0.tgz
    version: 0.2.0
  tomcat:
  - apiVersion: v1
    created: 2018-07-17T09:41:33.954863+02:00
    description: Tomcat for Linux
    digest: 30045c45c1b544bfd61716f6ccb1c3d4c326c80e80f70d51dc4964e8c32b1b97
    home: https://hub.docker.com/_/tomcat/
    icon: http://tomcat.apache.org/images/tomcat.png
    name: tomcat
    sources:
    - https://github.com/docker-library/tomcat
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/tomcat-9.0.tgz
    version: "9.0"
  ucd-agent:
  - apiVersion: v1
    appVersion: 7.0.0
    created: 2018-07-17T09:41:33.95514+02:00
    description: A Helm chart for IBM UrbanCode Deploy Agent
    digest: aef0b473e22595fecebd530e65439ab99f3477b8fc6f8c55b675c97f717d6f12
    icon: https://github.com/niklaushirt/charts/blob/master/helm/charts/icons/urbancodedeployicon.png
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: ucd-agent
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/ucd-agent-1.0.2.tgz
    version: 1.0.2
  ucd-server:
  - apiVersion: v1
    appVersion: 7.0.0
    created: 2018-07-17T09:41:33.955405+02:00
    description: A Helm chart for IBM UrbanCode Deploy
    digest: cc8164b99eaf6fdbeb4f166ef7e27104e4f476e7570a07e494c01146d6a7a248
    icon: https://github.com/niklaushirt/charts/blob/master/helm/charts/icons/urbancodedeployicon.png
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: ucd-server
    sources:
    - https://github.com/niklaushirt/charts
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/ucd-server-1.0.0.tgz
    version: 1.0.0
  velocity:
  - apiVersion: v1
    created: 2018-07-17T09:41:33.955738+02:00
    description: Deploys UrbanCode Velocity
    digest: f33e68b6e259b8e558fae3bf096178b7d131120fea05accb93c3d12f0d7435d4
    name: velocity
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/helm/charts/repo/stable/velocity-1.0.0.tgz
    version: 1.0.0
generated: 2018-07-17T09:41:33.941233+02:00
