apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "velocity.consumer.name" . }}
  labels:
    app: {{ template "velocity.consumer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "velocity.consumer.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          ports:
            - containerPort: 6004
          env:
            - name: MONGO_URL
              value: {{ .Values.mongo.url }}
            - name: ENCRYPT_KEY
              value: {{ .Values.encrypt.key }}
            - name: CONSUMER_URL
              value: {{ template "velocity.consumer.url" . }}
            - name: HELM_VERSION
              value: {{ .Chart.Version }}
            - name: LOG_LEVEL
              value: {{ .Values.loglevel }}
          # livenessProbe:
          #   httpGet:
          #     path: /ping
          #     port: 6004
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /ping
          #     port: 6004
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 2
          #   periodSeconds: 5
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "velocity.ui.name" . }}
  labels:
    app: {{ template "velocity.ui.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "velocity.ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "velocity.ui.name" . }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: ROOT_URL
              value: {{ template "velocity.ui.url" . }}
            - name: PORT
              value: "80"
            - name: SSLPORT
              value: "443"
            {{- if eq .Values.url.protocol "http" }}
            - name: DISABLE_SSL
              value: "true"
            {{- end }}
            - name: DDP_DEFAULT_CONNECTION_URL
              value: {{ template "velocity.ui.url" . }}
            - name: MONGO_URL
              value: {{ .Values.mongo.url }}
            - name: ENCRYPT_KEY
              value: {{ .Values.encrypt.key }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.adminpassword }}
            - name: HELM_VERSION
              value: {{ .Chart.Version }}
            - name: ACCESS_KEY
              value: {{ .Values.access.key }}
            - name: LOG_LEVEL
              value: {{ .Values.loglevel }}
          # livenessProbe:
          #   httpGet:
          #     path: /home
          #     port: 80
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 3
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /velocity
          #     port: 80
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 3
          #   periodSeconds: 10
