apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ template "fullname" . }}
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: "{{ .Release.Service }}"
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ template "fullname" . }}
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: mycluster.icp:8500/default/ucda:{{ .Values.tag }}
        env:
        - name: AGENT_NAME
          value: {{ .Values.agentname }}
        - name: SERVER_ADDR
          value: {{ .Values.serveradress }}
        resources: {}
      restartPolicy: Always
status: {}
