###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

{{ if and .Values.persistence.enabled (not .Values.homePVC.existingClaimName) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.homePVC.name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.persistence.useDynamicProvisioning }}
  ## if present, use the storageClassName from the values.yaml, else use the
  ## default storageClass setup by Kubernetes Administrator
  ##
  ## setting storageClassName to nil means use the default storage class 
  storageClassName: {{ default nil .Values.homePVC.storageClassName | quote }}
  {{- else }}
  ## disable dynamic provisioning
  storageClassName: ""
  {{- if .Values.homePVC.selector.label }}
  # use selectors in the binding process
  selector:
    matchExpressions:
      - {key: {{ .Values.homePVC.selector.label }}, operator: In, values: [{{ .Values.homePVC.selector.value }}]}
  {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.homePVC.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.homePVC.size | quote }}
{{- end }}
