#*******************************************************************************
# Licensed Materials - Property of IBM
# "Restricted Materials of IBM"
#
# Copyright IBM Corp. 2017 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#*******************************************************************************

name: microclimate
version: 1.0.0
description: End to end development environment for rapidly creating, developing and deploying applications.
tillerVersion: ">=2.6.0"
appVersion: 18.03
