#*******************************************************************************
# Licensed Materials - Property of IBM
# "Restricted Materials of IBM"
#
# Copyright IBM Corp. 2017 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#*******************************************************************************

name: microclimate
version: 0.1.0-beta
description: Environment for end to end development, from code generation to cloud deployment.
tillerVersion: ">=2.4.0"
