---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
    fabric8.io/git-commit: f7967da2069f486a3e6dbef233574eccac3e0dae
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=manageiq&var-version=2.2.327
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/manageiq
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/manageiq
    fabric8.io/git-branch: release-v2.2.327
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/manageiq
    fabric8.io/scm-tag: fabric8-devops-2.0.1
  labels:
    provider: fabric8
    project: manageiq
    version: 2.2.327
    group: io.fabric8.devops.apps
  name: manageiq
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: fabric8
      project: manageiq
      group: io.fabric8.devops.apps
      version: 2.2.327
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: f7967da2069f486a3e6dbef233574eccac3e0dae
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=manageiq&var-version=2.2.327
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/manageiq
        fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/manageiq
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.2.327
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/manageiq
        fabric8.io/scm-tag: fabric8-devops-2.0.1
      labels:
        provider: fabric8
        project: manageiq
        version: 2.2.327
        group: io.fabric8.devops.apps
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: manageiq/manageiq:latest
        imagePullPolicy: IfNotPresent
        name: manageiq
        readinessProbe:
          httpGet:
            path: /
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          privileged: true
