---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/manageiq/src/main/fabric8/icon.png
    fabric8.io/app-menu: management
    fabric8.io/git-commit: f7967da2069f486a3e6dbef233574eccac3e0dae
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/manageiq
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/manageiq
    fabric8.io/git-branch: release-v2.2.327
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/manageiq
    fabric8.io/scm-tag: fabric8-devops-2.0.1
  labels:
    provider: fabric8
    project: manageiq
    version: 2.2.327
    group: io.fabric8.devops.apps
    expose: "true"
  name: manageiq
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    project: manageiq
    provider: fabric8
    group: io.fabric8.devops.apps
