description: Nginx for Linux
home: https://github.com/kubernetes/helm
icon: https://pbs.twimg.com/profile_images/567774844322713600/tYoVju31.png
keywords:
- http
- nginx
- www
- web
maintainers:
- email: guo@ca.ibm.com
  name: guo
name: nginx
sources:
- https://hub.docker.com/_/nginx/
version: 1.8.1
