# Default values for gitlab-ce.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: gitlab/gitlab-ce:9.3.8-ce.0
  pullPolicy: IfNotPresent
service:
  name: gitlab-ce
  type: NodePort
