###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

name: jenkins
description: The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.
version: 2.19.4
home: https://jenkins.io/
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
keyworkds:
  - jenkins
  - ci
  - build
  - automation
sources:
  - https://github.com/jenkinsci/jenkins
  - https://github.com/jenkinsci/docker-jnlp-slave
  - https://github.com/jenkinsci/kubernetes-plugin
maintainers:
  - name: IBM Cloud Private
engine: gotpl
tillerVersion: ">=2.6.0"
apiVersion: v1
