## Metadata for RabbitMQ configuration
## This metadata is used to augment the value.yaml to drive ICP UI for configuration of the Helm chart installation

arch:
 __metadata:
   name: "arch"
   label: "Architecture"
   description: "Worker node architecture to deploy to. Choose an explicit architecture here to override it."
   type: "string"
   immutable: "false"
   required: false
   options:
     - label: "amd64"
       value: "amd64"
     - label: "ppc64le"
       value: "ppc64le"

## Jenkins master configuration
master:
  __metadata:
    label: "Jenkins master configuration"

  ## Image configuration metadata
  image:
    __metadata:
      label: "Jenkins master image"
    repository:
      __metadata:
        name: "repository"
        label: "Docker repository"
        description: "Docker repository to pull the master image from."
        type: "string"
        immutable: "false"
        required: true
    tag:
      __metadata:
        name: "tag"
        label: "Tag"
        description: "Docker master image tag to pull"
        type: "string"
        immutable: "false"
        required: true
    pullPolicy:
      __metadata:
        name: "pullPolicy"
        label: "Docker master image pull policy"
        description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
        type: "string"
        immutable: "false"
        required: true
        options:
        - label: "IfNotPresent"
          value: "IfNotPresent"
        - label: "Always"
          value: "Always"
        - label: "Never"
          value: "Never"

  adminUser:
    __metadata:
      name: "adminUser"
      label: "Admin user"
      description: "Jenkins admin user. Default is 'admin'."
      type: "string"
      immutable: "false"
      required: true
  adminPassword:
    __metadata:
      name: "adminPassword"
      label: "Admin password"
      description: "Jenkins admin password. Default is 'admin'."
      type: "password"
      immutable: "false"
      required: true
    
  service:
    __metadata:
      label: "Service configuration"
    name:
      __metadata:
        name: "name"
        label: "Jenkins service port name"
        type: "string"
        immutable: "false"
        required: true
    type:
      __metadata:
        name: "type"
        label: "Service type"
        description: "NodePort, LoadBalancer, or ClusterIP. Defaults to NodePort."
        type: "string"
        immutable: "false"
        required: true
        options:
        - label: "NodePort"
          value: "NodePort"
        - label: "LoadBalancer"
          value: "LoadBalancer"
        - label: "ClusterIP"
          value: "ClusterIP"
    externalPort:
      __metadata:
        name: "externalPort"
        label: "Jenkins external port"
        description: "Jenkins UI port in the cluster."
        type: "string"
        immutable: "false"
        required: true
    internalPort:
      __metadata:
        name: "internalPort"
        label: "Jenkins internal port"
        description: "Jenkins UI port in the container."
        type: "string"
        immutable: "false"
        required: true

  agentListenerPort:
    __metadata:
      name: "agentListenerPort"
      label: "Jenkins agent listener port"
      description: "Jenkins agent listener port in the cluster."
      type: "string"
      immutable: "false"
      required: true
  
  resourceConstraints.enabled:
    __metadata: 
      label: "Enable Jenkins master resource constraints"
      type: "boolean"
      required: true   
  
  ## Resource requests and limits configuration metadata
  resources:
    __metadata:
      label: "Resource configuration"
    requests:
      cpu: 
        __metadata: 
          label: "CPU request"
          description: "The CPU request"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory request"
          description: "The memory request"
          type: "string"
          required: true
    limits:
      cpu: 
        __metadata: 
          label: "CPU limit"
          description: "The CPU limit"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory limit"
          description: "The memory limit"
          type: "string"
          required: true


## Jenkins agent configuration
agent:
  __metadata:
    label: "Jenkins agent configuration"
  ## Image configuration metadata
  image:
    __metadata:
      label: "Jenkins agent image"
    repository:
      __metadata:
        name: "repository"
        label: "Docker repository"
        description: "Docker repository to pull the agent image from."
        type: "string"
        immutable: "false"
        required: true
    tag:
      __metadata:
        name: "tag"
        label: "Tag"
        description: "Docker agent image tag to pull"
        type: "string"
        immutable: "false"
        required: true
    
  resourceConstraints.enabled:
    __metadata: 
      label: "Enable Jenkins agent resource constraints"
      type: "boolean"
      required: true   
  
  ## Resource requests and limits configuration metadata
  resources:
    __metadata:
      label: "Resource configuration"
    requests:
      cpu: 
        __metadata: 
          label: "CPU request"
          description: "The CPU request"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory request"
          description: "The memory request"
          type: "string"
          required: true
    limits:
      cpu: 
        __metadata: 
          label: "CPU limit"
          description: "The CPU limit"
          type: "string"
          required: true   
      memory: 
        __metadata: 
          label: "Memory limit"
          description: "The memory limit"
          type: "string"
          required: true

## Persistence options
persistence:
  __metadata:
    label: "Data persistence configuration"
  enabled:
    __metadata:
      name: "enabled"
      label: "Enable persistence for this deployment"
      description: "Enables persistence for this deployment. Defaults to false. A persistent volume is required."
      type: "boolean"
      immutable: "false"
      required: true
  useDynamicProvisioning:
   __metadata:
      name: "useDynamicProvisioning"
      label: "Use dynamic provisioning for persistent volume"
      description: "If dynamic provisioning is available in the cluster this option will automatically provision the requested volume if set to true. Defaults to false."
      type: "boolean"
      immutable: "false"
      required: true

homePVC:
  __metadata:
    label: "PVC configuration"
  existingClaimName:
    __metadata:
      name: "existingClaimName"
      label: "Existing volume claim"
      description: "By default a new persistent volume claim will be created. Specify an existing claim here if one is available."
      type: "string"
      immutable: "false"
      required: false
  selector:
    __metadata:
      label: "Enable a volume selector"
    label:
      __metadata:
        name: "label"
        label: "Field to select the volume"
        type: "string"
        immutable: "false"
        required: false
    value:
      __metadata:
        name: "value"
        label: "Value of the field to select the volume"
        type: "string"
        immutable: "false"
        required: false
  storageClassName:
    __metadata:
      name: "storageClassName"
      label: "Storage class name"
      description: "Choose a specific storage class name. Defaults to the default storage class in the cluster."
      type: "string"
      immutable: "false"
      required: false
  accessMode:
    __metadata:
      name: "accessMode"
      label: "Storage access mode"
      description: "Use volume as ReadOnlyMany or ReadWriteOnce. Default is ReadWriteOnce."
      type: "string"
      immutable: "false"
      required: true
      options:
      - label: "ReadWriteOnce"
        value: "ReadWriteOnce"
      - label: "ReadOnlyMany"
        value: "ReadOnlyMany"
  size:
    __metadata:
      name: "size"
      label: "Size of the volume claim"
      description: "Defaults to 1Gi of storage request. Choose a different size of disk if needed."
      type: "string"
      immutable: "false"
      required: true
      
rbac:
  __metadata:
    label: "RBAC roles and bindings"
  install:
    __metadata:
      name: "install"
      label: "Install"
      description: "Install RBAC roles and bindings"
      type: "boolean"
      immutable: "false"
      required: true
  serviceAccountName:
    __metadata:
      name: "serviceAccountName"
      label: "Existing ClusterRoleBinding name"
      description: "The name of an existing ClusterRoleBinding to use if not installing"
      type: "boolean"
      immutable: "false"
      required: true
  apiVersion:
    __metadata:
      name: "apiVersion"
      label: "ClusterRoleBinding API version"
      description: "Version of the ClusterRoleBinding API to install. (currently either v1beta1 or v1alpha1)"
      type: "string"
      immutable: "false"
      required: true
  roleRef:
    __metadata:
      name: "roleRef"
      label: "Cluster role"
      description: "Name of the cluster role to bind. Default is cluster-admin"
      type: "string"
      immutable: "false"
      required: true
