# Default values for tomcat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: tomcat
  tag: "9.0"
  pullPolicy: IfNotPresent
service:
  name: tomcat
  type: NodePort
  externalPort: 8080
  internalPort: 8080
enableResourceConstraints: false
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi
