{{- if .Values.jenkins.Master.UseSecurity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.jenkins.Master.AdminPassword }}
  jenkins-admin-password: {{ .Values.jenkins.Master.AdminPassword | b64enc | quote }}
  {{ else }}
  jenkins-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  jenkins-admin-user: {{ .Values.jenkins.Master.AdminUser | b64enc | quote }}
  {{ if .Values.jenkins.Master.UseSecurity }}
  jenkins-admin-api-token: {{ "be652e0e60b0af067c2b54cd04720df3" | b64enc | quote }}
  {{ end }}
{{- end }}
