#*******************************************************************************
# Licensed Materials - Property of IBM
# "Restricted Materials of IBM"
#
# Copyright IBM Corp. 2017 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#*******************************************************************************

apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" .}}
  labels:
    app: {{ template "name" .}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
    - port: 8888
      name: orion-http
    - port: 9090
      name: portal-http
  selector:
    name: {{ template "name" .}}
