apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: {{ template "fullname" . }}
status:
  loadBalancer: {}
