apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ template "fullname" . }}
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: "{{ .Release.Service }}"
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: "{{ .Release.Service }}"
        io.kompose.service: {{ template "fullname" . }}
    spec:
      containers:
      - image: mycluster.icp:8500/default/ucds:{{ .Values.image.tag }}
        name: {{ template "fullname" . }}
        ports:
        - containerPort: 8443
        - containerPort: 7918
        - containerPort: 7919
        resources: {}
        env:
        - name: SERVER_ADDR
          value: "{{ .Values.server.nodeport.address }}"
        - name: SERVER_PORT_UI
          value: "{{ .Values.server.nodeport.ui }}"
        - name: SERVER_PORT_JMS
          value: "{{ .Values.server.nodeport.jms }}"
        - name: SERVER_PORT_HTTP
          value: "{{ .Values.server.nodeport.http }}"
      restartPolicy: Always
status: {}
