apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  type: "{{ .Values.server.serviceType }}"
  ports:
  - name: "https"
    port: 8443
    targetPort: 8443
    nodePort: {{ .Values.server.nodeport.ui }}
  - name: "agentjms"
    port: 7918
    targetPort: 7918
    nodePort: {{ .Values.server.nodeport.jms }}
  - name: "agenthttp"
    port: 7919
    targetPort: 7919
    nodePort: {{ .Values.server.nodeport.http }}

  selector:
    io.kompose.service: {{ template "fullname" . }}
status:
  loadBalancer: {}
