# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.repository_ucds: ibmcom/ucds

# Version  for UrbanCode Deploy Server
tag: 6.2.7.1.960481

#Number of replicas for UrbanCode Deploy Server
replicaCount_Agent: 1


#Service Type for UrbanCode Deploy Server
serviceType: "NodePort"
